name: acda_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2

  # State Management
  flutter_riverpod: 2.3.6

  # Networking
  retrofit: 4.0.1
  dio: 5.3.2
  connectivity_plus: 4.0.1
  internet_connection_checker: 1.0.0+1

  # Navigation
  go_router: 9.0.0

  # Firebase
  firebase_core: 2.14.0
  firebase_crashlytics: 3.3.3

  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  injectable: 2.1.2
  retrofit_generator: 5.0.0
  flutter_flavorizr: 2.2.1
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.1
  dotted_border: 2.0.0+3
  image_picker: 1.0.0
  modal_bottom_sheet: 3.0.0-pre
  loader_overlay: 2.2.0
  flutter_secure_storage: 8.0.0
  animated_text_kit: ^4.2.2
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.5
  freezed: 2.3.5
  json_serializable: 6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic

flavorizr:
  flavors:
    dev:
      app:
        name: "ACDA_dev"
      android:
        applicationId: "com.acda.dev"
      ios:
        bundleId: "com.acda.dev"
    stg:
      app:
        name: "ACDA_stg"
      android:
        applicationId: "com.acda.stg"
      ios:
        bundleId: "com.acda.stg"
    prd:
      app:
        name: "ACDA"
      android:
        applicationId: "com.acda"
      ios:
        bundleId: "com.acda"

flutter_launcher_icons:
  image_path: "assets/icons/ACDA-AppIcon-iOS.png"

  android: "launcher_icon"
  image_path_android: "assets/icons/ACDA-AppIcon-Andriod.png"
  adaptive_icon_background: "#0c4aad"

  ios: true
  image_path_ios: "assets/icons/ACDA-AppIcon-iOS.png"
  remove_alpha_ios: true
