// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('webAPIKey'),
    appId: '1:584876387850:web:3243313b0c966e1d7279f3',
    messagingSenderId: '584876387850',
    projectId: 'muict-sp-acda-stg',
    authDomain: 'muict-sp-acda-stg.firebaseapp.com',
    storageBucket: 'muict-sp-acda-stg.appspot.com',
    measurementId: 'G-41KZVXQLY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('androidAPIKey'),
    appId: '1:584876387850:android:78576f8dcc04582e7279f3',
    messagingSenderId: '584876387850',
    projectId: 'muict-sp-acda-stg',
    storageBucket: 'muict-sp-acda-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('iosAPIKey'),
    appId: '1:584876387850:ios:b0f5ec4986456c557279f3',
    messagingSenderId: '584876387850',
    projectId: 'muict-sp-acda-stg',
    storageBucket: 'muict-sp-acda-stg.appspot.com',
    iosClientId: '584876387850-grnlmm3sdsgi8cstcq7jc5015uhn7gne.apps.googleusercontent.com',
    iosBundleId: 'com.acda.stg',
  );
}
